/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jorgealvarez_lab6;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ofici
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ListarBg = new javax.swing.ButtonGroup();
        ModificarBg = new javax.swing.ButtonGroup();
        AgregarJefe = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        NombreAgregarJefeTf = new javax.swing.JTextField();
        IDAgregarJefeTf = new javax.swing.JTextField();
        EdadAgregarJefeTf = new javax.swing.JTextField();
        NacionalidadAgregarJefeTf = new javax.swing.JTextField();
        LugarDeNacimientoAgregarJefeTf = new javax.swing.JTextField();
        AgregarJefeAgregarJefeBt = new javax.swing.JButton();
        ColorDePielAgregarJefeBt = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTree3 = new javax.swing.JTree();
        jLabel16 = new javax.swing.JLabel();
        SeccionDeTrabajoAgregarJefeCb = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        AgregarEmpleadoAgregarJefeCb = new javax.swing.JComboBox<>();
        AgregarEmpleadoAgregarJefeBt = new javax.swing.JButton();
        AgregarEmpleado = new javax.swing.JDialog();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        NombreAgregarEmpleadoTf = new javax.swing.JTextField();
        IDAgregarEmpleadoTf = new javax.swing.JTextField();
        EdadAgregarEmpleadoTf = new javax.swing.JTextField();
        NacionalidadAgregarEmpleadoTf = new javax.swing.JTextField();
        LugarDeNacimientoAgregarEmpleadoTf = new javax.swing.JTextField();
        AgregarEmpleadoAgregarEmpleadoBt = new javax.swing.JButton();
        ColorDePielAgregarEmpleadoBt = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTree4 = new javax.swing.JTree();
        jLabel26 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        HoraDeLlegadaAgregarEmpleadoSp = new javax.swing.JSpinner();
        jLabel28 = new javax.swing.JLabel();
        HoraDeSalidaAgregarEmpleadoSp = new javax.swing.JSpinner();
        jLabel29 = new javax.swing.JLabel();
        SueldoAgregarEmpleadoTf = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        EstadoAgregarEmpleadoCb = new javax.swing.JComboBox<>();
        AgregarCliente = new javax.swing.JDialog();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        NombreAgregarClienteTf = new javax.swing.JTextField();
        IDAgregarClienteTf = new javax.swing.JTextField();
        EdadAgregarClienteTf = new javax.swing.JTextField();
        NacionalidadAgregarClienteTf = new javax.swing.JTextField();
        LugarDeNacimientoAgregarClienteTf = new javax.swing.JTextField();
        AgregarClienteAgregarClienteBt = new javax.swing.JButton();
        ColorDePielAgregarClienteBt = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTree5 = new javax.swing.JTree();
        jLabel39 = new javax.swing.JLabel();
        DineroAgregarClienteTf = new javax.swing.JTextField();
        AgregarFamiliar = new javax.swing.JDialog();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        NombreAgregarFamiliarTf = new javax.swing.JTextField();
        IDAgregarFamiliarTf = new javax.swing.JTextField();
        EdadAgregarFamiliarTf = new javax.swing.JTextField();
        NacionalidadAgregarFamiliarTf = new javax.swing.JTextField();
        LugarDeNacimientoAgregarFamiliarTf = new javax.swing.JTextField();
        AgregarFamiliarAgregarFamiliarBt = new javax.swing.JButton();
        ColorDePielAgregarFamiliarBt = new javax.swing.JButton();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        FamiliarPadreAgregarFamiliarCb = new javax.swing.JComboBox<>();
        FamiliarHijoAgregarFamiliarCb = new javax.swing.JComboBox<>();
        AgregarFamiliarHijoAgregarFamiliarBt = new javax.swing.JButton();
        AgregarFamiliarBg = new javax.swing.ButtonGroup();
        AgregarFamiliarBg1 = new javax.swing.ButtonGroup();
        AgregarGato = new javax.swing.JDialog();
        jLabel46 = new javax.swing.JLabel();
        PesoAgregarGatoTf = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        AlturaAgregarGatoTf = new javax.swing.JTextField();
        AgregarGatoAgregarGatoBt = new javax.swing.JButton();
        jLabel52 = new javax.swing.JLabel();
        PrecioAgregarGatoTf = new javax.swing.JTextField();
        AgregarBaleada = new javax.swing.JDialog();
        jLabel51 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        PrecioAgregarBaleadaTf = new javax.swing.JTextField();
        IngredienteAgregarBaleadaTf = new javax.swing.JTextField();
        AgregarIngredienteAgregarBaleadaBt = new javax.swing.JButton();
        AgregarBaleadaAgregarBaleadaBt = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JefeAgregarBt = new javax.swing.JButton();
        EmpleadoAgregarBt = new javax.swing.JButton();
        ClienteAgregarBt = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        FamiliarAgregarBt = new javax.swing.JButton();
        GatoAgregarBt = new javax.swing.JButton();
        BaleadaAgregarBt = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTree2 = new javax.swing.JTree();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JefesListarRb = new javax.swing.JRadioButton();
        EmpleadosListarRb = new javax.swing.JRadioButton();
        ClientesListarRb = new javax.swing.JRadioButton();
        FamiliaresListarRb = new javax.swing.JRadioButton();
        GatosListarRb = new javax.swing.JRadioButton();
        BaleadasListarRb = new javax.swing.JRadioButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        TablaListar = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        JefesModificarRb = new javax.swing.JRadioButton();
        EmpleadosModificarRb = new javax.swing.JRadioButton();
        ClientesModificarRb = new javax.swing.JRadioButton();
        FamiliaresModificarRb = new javax.swing.JRadioButton();
        GatosModificarRb = new javax.swing.JRadioButton();
        BaleadasModificarRb = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        ActualizarControlesModificarBt = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        jLabel8.setText("Edad");

        jLabel9.setText("ID");

        jLabel10.setText("Nacionalidad");

        jLabel11.setText("Lugar de nacimiento");

        jLabel13.setText("Nombre");

        jLabel14.setText("Arbol genealógico");

        jLabel15.setText("Color de piel");

        AgregarJefeAgregarJefeBt.setText("Agregar Jefe");
        AgregarJefeAgregarJefeBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarJefeAgregarJefeBtActionPerformed(evt);
            }
        });

        jScrollPane5.setViewportView(jTree3);

        jLabel16.setText("Sección de Trabajo");

        SeccionDeTrabajoAgregarJefeCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cocina", "Venta de baleadas", "Venta de gatos" }));

        jLabel17.setText("Empleado");

        AgregarEmpleadoAgregarJefeBt.setText("Agregar Empleado");
        AgregarEmpleadoAgregarJefeBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarEmpleadoAgregarJefeBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AgregarJefeLayout = new javax.swing.GroupLayout(AgregarJefe.getContentPane());
        AgregarJefe.getContentPane().setLayout(AgregarJefeLayout);
        AgregarJefeLayout.setHorizontalGroup(
            AgregarJefeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarJefeLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(AgregarJefeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(AgregarJefeLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12))
                    .addComponent(jLabel11)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addGap(31, 31, 31)
                .addGroup(AgregarJefeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AgregarJefeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(NombreAgregarJefeTf)
                        .addComponent(IDAgregarJefeTf)
                        .addComponent(EdadAgregarJefeTf)
                        .addComponent(NacionalidadAgregarJefeTf)
                        .addComponent(LugarDeNacimientoAgregarJefeTf)
                        .addComponent(ColorDePielAgregarJefeBt, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SeccionDeTrabajoAgregarJefeCb, 0, 200, Short.MAX_VALUE)
                        .addComponent(AgregarEmpleadoAgregarJefeCb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(AgregarEmpleadoAgregarJefeBt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(AgregarJefeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14)
                    .addGroup(AgregarJefeLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(AgregarJefeAgregarJefeBt, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane5))
                .addContainerGap())
        );
        AgregarJefeLayout.setVerticalGroup(
            AgregarJefeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarJefeLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(AgregarJefeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(NombreAgregarJefeTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(AgregarJefeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AgregarJefeLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(AgregarJefeAgregarJefeBt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(AgregarJefeLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(AgregarJefeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(IDAgregarJefeTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AgregarJefeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(EdadAgregarJefeTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AgregarJefeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(NacionalidadAgregarJefeTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AgregarJefeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(LugarDeNacimientoAgregarJefeTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(AgregarJefeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AgregarJefeLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel12))
                            .addGroup(AgregarJefeLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(ColorDePielAgregarJefeBt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AgregarJefeLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel15)))
                        .addGap(18, 18, 18)
                        .addGroup(AgregarJefeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SeccionDeTrabajoAgregarJefeCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(AgregarJefeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(AgregarEmpleadoAgregarJefeCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AgregarEmpleadoAgregarJefeBt)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jLabel18.setText("Edad");

        jLabel19.setText("ID");

        jLabel20.setText("Nacionalidad");

        jLabel21.setText("Lugar de nacimiento");

        jLabel23.setText("Nombre");

        jLabel24.setText("Arbol genealógico");

        jLabel25.setText("Color de piel");

        AgregarEmpleadoAgregarEmpleadoBt.setText("Agregar Empleado");
        AgregarEmpleadoAgregarEmpleadoBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarEmpleadoAgregarEmpleadoBtActionPerformed(evt);
            }
        });

        jScrollPane6.setViewportView(jTree4);

        jLabel26.setText("Sección de Trabajo");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Venta de baleadas", "Venta de gatos" }));

        jLabel27.setText("Hora de llegada(24h)");

        jLabel28.setText("Hora de salida(24h)");

        jLabel29.setText("Sueldo(L.)");

        jLabel30.setText("Estado");

        EstadoAgregarEmpleadoCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disponible", "Ocupado" }));

        javax.swing.GroupLayout AgregarEmpleadoLayout = new javax.swing.GroupLayout(AgregarEmpleado.getContentPane());
        AgregarEmpleado.getContentPane().setLayout(AgregarEmpleadoLayout);
        AgregarEmpleadoLayout.setHorizontalGroup(
            AgregarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarEmpleadoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(AgregarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addGroup(AgregarEmpleadoLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22))
                    .addComponent(jLabel21)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18)
                    .addComponent(jLabel20)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30))
                .addGap(31, 31, 31)
                .addGroup(AgregarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NombreAgregarEmpleadoTf)
                    .addComponent(IDAgregarEmpleadoTf)
                    .addComponent(EdadAgregarEmpleadoTf)
                    .addComponent(NacionalidadAgregarEmpleadoTf)
                    .addComponent(LugarDeNacimientoAgregarEmpleadoTf)
                    .addComponent(ColorDePielAgregarEmpleadoBt, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox4, 0, 200, Short.MAX_VALUE)
                    .addComponent(HoraDeLlegadaAgregarEmpleadoSp)
                    .addComponent(HoraDeSalidaAgregarEmpleadoSp)
                    .addComponent(SueldoAgregarEmpleadoTf)
                    .addComponent(EstadoAgregarEmpleadoCb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(AgregarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel24)
                    .addGroup(AgregarEmpleadoLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(AgregarEmpleadoAgregarEmpleadoBt, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane6))
                .addContainerGap())
        );
        AgregarEmpleadoLayout.setVerticalGroup(
            AgregarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarEmpleadoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(AgregarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(NombreAgregarEmpleadoTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(AgregarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AgregarEmpleadoLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(AgregarEmpleadoAgregarEmpleadoBt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(AgregarEmpleadoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(AgregarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(IDAgregarEmpleadoTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AgregarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(EdadAgregarEmpleadoTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AgregarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(NacionalidadAgregarEmpleadoTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AgregarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(LugarDeNacimientoAgregarEmpleadoTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(AgregarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AgregarEmpleadoLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel22))
                            .addGroup(AgregarEmpleadoLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(ColorDePielAgregarEmpleadoBt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AgregarEmpleadoLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel25)))
                        .addGap(18, 18, 18)
                        .addGroup(AgregarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26))
                        .addGap(18, 18, 18)
                        .addGroup(AgregarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(HoraDeLlegadaAgregarEmpleadoSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AgregarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(HoraDeSalidaAgregarEmpleadoSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AgregarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(SueldoAgregarEmpleadoTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AgregarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(EstadoAgregarEmpleadoCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jLabel31.setText("Edad");

        jLabel32.setText("ID");

        jLabel33.setText("Nacionalidad");

        jLabel34.setText("Lugar de nacimiento");

        jLabel36.setText("Nombre");

        jLabel37.setText("Arbol genealógico");

        jLabel38.setText("Color de piel");

        AgregarClienteAgregarClienteBt.setText("Agregar Cliente");
        AgregarClienteAgregarClienteBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarClienteAgregarClienteBtActionPerformed(evt);
            }
        });

        jScrollPane7.setViewportView(jTree5);

        jLabel39.setText("Dinero");

        javax.swing.GroupLayout AgregarClienteLayout = new javax.swing.GroupLayout(AgregarCliente.getContentPane());
        AgregarCliente.getContentPane().setLayout(AgregarClienteLayout);
        AgregarClienteLayout.setHorizontalGroup(
            AgregarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarClienteLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(AgregarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel36)
                    .addGroup(AgregarClienteLayout.createSequentialGroup()
                        .addComponent(jLabel38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel35))
                    .addComponent(jLabel34)
                    .addComponent(jLabel32)
                    .addComponent(jLabel31)
                    .addComponent(jLabel33)
                    .addComponent(jLabel39))
                .addGap(36, 36, 36)
                .addGroup(AgregarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NombreAgregarClienteTf, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(IDAgregarClienteTf)
                    .addComponent(EdadAgregarClienteTf)
                    .addComponent(NacionalidadAgregarClienteTf)
                    .addComponent(LugarDeNacimientoAgregarClienteTf)
                    .addComponent(ColorDePielAgregarClienteBt, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DineroAgregarClienteTf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(AgregarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel37)
                    .addGroup(AgregarClienteLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(AgregarClienteAgregarClienteBt, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane7))
                .addContainerGap())
        );
        AgregarClienteLayout.setVerticalGroup(
            AgregarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarClienteLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(AgregarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(jLabel37)
                    .addComponent(NombreAgregarClienteTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(AgregarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AgregarClienteLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(AgregarClienteAgregarClienteBt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(AgregarClienteLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(AgregarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(IDAgregarClienteTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AgregarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31)
                            .addComponent(EdadAgregarClienteTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AgregarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(NacionalidadAgregarClienteTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AgregarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel34)
                            .addComponent(LugarDeNacimientoAgregarClienteTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(AgregarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AgregarClienteLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel35))
                            .addGroup(AgregarClienteLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(ColorDePielAgregarClienteBt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AgregarClienteLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel38)))
                        .addGap(18, 18, 18)
                        .addGroup(AgregarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel39)
                            .addComponent(DineroAgregarClienteTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jLabel40.setText("Edad");

        jLabel41.setText("ID");

        jLabel42.setText("Nacionalidad");

        jLabel43.setText("Lugar de nacimiento");

        jLabel45.setText("Nombre");

        jLabel47.setText("Color de piel");

        AgregarFamiliarAgregarFamiliarBt.setText("Agregar Familiar");
        AgregarFamiliarAgregarFamiliarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarFamiliarAgregarFamiliarBtActionPerformed(evt);
            }
        });

        jLabel49.setText("Familiar Padre");

        jLabel50.setText("Familiar Hijo");

        AgregarFamiliarHijoAgregarFamiliarBt.setText("Agregar Familiar Hijo");
        AgregarFamiliarHijoAgregarFamiliarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarFamiliarHijoAgregarFamiliarBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AgregarFamiliarLayout = new javax.swing.GroupLayout(AgregarFamiliar.getContentPane());
        AgregarFamiliar.getContentPane().setLayout(AgregarFamiliarLayout);
        AgregarFamiliarLayout.setHorizontalGroup(
            AgregarFamiliarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarFamiliarLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(AgregarFamiliarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel45)
                    .addGroup(AgregarFamiliarLayout.createSequentialGroup()
                        .addComponent(jLabel47)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel44))
                    .addComponent(jLabel43)
                    .addComponent(jLabel41)
                    .addComponent(jLabel40)
                    .addComponent(jLabel42))
                .addGap(36, 36, 36)
                .addGroup(AgregarFamiliarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NombreAgregarFamiliarTf, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(IDAgregarFamiliarTf)
                    .addComponent(EdadAgregarFamiliarTf)
                    .addComponent(NacionalidadAgregarFamiliarTf)
                    .addComponent(ColorDePielAgregarFamiliarBt, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LugarDeNacimientoAgregarFamiliarTf))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AgregarFamiliarLayout.createSequentialGroup()
                .addGroup(AgregarFamiliarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AgregarFamiliarLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AgregarFamiliarAgregarFamiliarBt, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AgregarFamiliarLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(AgregarFamiliarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel49)
                            .addComponent(jLabel50))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addGroup(AgregarFamiliarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AgregarFamiliarHijoAgregarFamiliarBt)
                            .addGroup(AgregarFamiliarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(FamiliarPadreAgregarFamiliarCb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(FamiliarHijoAgregarFamiliarCb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        AgregarFamiliarLayout.setVerticalGroup(
            AgregarFamiliarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarFamiliarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(AgregarFamiliarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(NombreAgregarFamiliarTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AgregarFamiliarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(IDAgregarFamiliarTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AgregarFamiliarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(EdadAgregarFamiliarTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AgregarFamiliarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(NacionalidadAgregarFamiliarTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AgregarFamiliarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(LugarDeNacimientoAgregarFamiliarTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(AgregarFamiliarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AgregarFamiliarLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel44))
                    .addGroup(AgregarFamiliarLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(ColorDePielAgregarFamiliarBt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AgregarFamiliarLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel47)))
                .addGap(18, 18, 18)
                .addGroup(AgregarFamiliarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel49)
                    .addComponent(FamiliarPadreAgregarFamiliarCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AgregarFamiliarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel50)
                    .addComponent(FamiliarHijoAgregarFamiliarCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(AgregarFamiliarHijoAgregarFamiliarBt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(AgregarFamiliarAgregarFamiliarBt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel46.setText("Peso");

        jLabel48.setText("Altura");

        AgregarGatoAgregarGatoBt.setText("Agregar Gato");
        AgregarGatoAgregarGatoBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarGatoAgregarGatoBtActionPerformed(evt);
            }
        });

        jLabel52.setText("Precio");

        javax.swing.GroupLayout AgregarGatoLayout = new javax.swing.GroupLayout(AgregarGato.getContentPane());
        AgregarGato.getContentPane().setLayout(AgregarGatoLayout);
        AgregarGatoLayout.setHorizontalGroup(
            AgregarGatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AgregarGatoLayout.createSequentialGroup()
                .addContainerGap(169, Short.MAX_VALUE)
                .addComponent(AgregarGatoAgregarGatoBt, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(AgregarGatoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(AgregarGatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel46)
                    .addComponent(jLabel48)
                    .addComponent(jLabel52))
                .addGap(36, 36, 36)
                .addGroup(AgregarGatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PesoAgregarGatoTf)
                    .addComponent(AlturaAgregarGatoTf)
                    .addComponent(PrecioAgregarGatoTf, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AgregarGatoLayout.setVerticalGroup(
            AgregarGatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarGatoLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(AgregarGatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel52)
                    .addComponent(PrecioAgregarGatoTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AgregarGatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PesoAgregarGatoTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel46))
                .addGap(18, 18, 18)
                .addGroup(AgregarGatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel48)
                    .addComponent(AlturaAgregarGatoTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(AgregarGatoAgregarGatoBt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel51.setText("Precio");

        jLabel53.setText("Ingrediente");

        AgregarIngredienteAgregarBaleadaBt.setText("Agregar Ingrediente");
        AgregarIngredienteAgregarBaleadaBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarIngredienteAgregarBaleadaBtActionPerformed(evt);
            }
        });

        AgregarBaleadaAgregarBaleadaBt.setText("Agregar Baleada");
        AgregarBaleadaAgregarBaleadaBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarBaleadaAgregarBaleadaBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AgregarBaleadaLayout = new javax.swing.GroupLayout(AgregarBaleada.getContentPane());
        AgregarBaleada.getContentPane().setLayout(AgregarBaleadaLayout);
        AgregarBaleadaLayout.setHorizontalGroup(
            AgregarBaleadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarBaleadaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(AgregarBaleadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel51)
                    .addComponent(jLabel53))
                .addGap(39, 39, 39)
                .addGroup(AgregarBaleadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AgregarIngredienteAgregarBaleadaBt)
                    .addGroup(AgregarBaleadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(PrecioAgregarBaleadaTf, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                        .addComponent(IngredienteAgregarBaleadaTf)))
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AgregarBaleadaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AgregarBaleadaAgregarBaleadaBt, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        AgregarBaleadaLayout.setVerticalGroup(
            AgregarBaleadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarBaleadaLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(AgregarBaleadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel51)
                    .addComponent(PrecioAgregarBaleadaTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AgregarBaleadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel53)
                    .addComponent(IngredienteAgregarBaleadaTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(AgregarIngredienteAgregarBaleadaBt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(AgregarBaleadaAgregarBaleadaBt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(jTree1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(444, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Inicio", jPanel1);

        jLabel1.setText("Agregar Personas");

        JefeAgregarBt.setText("Jefe");
        JefeAgregarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JefeAgregarBtActionPerformed(evt);
            }
        });

        EmpleadoAgregarBt.setText("Empleado");
        EmpleadoAgregarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpleadoAgregarBtActionPerformed(evt);
            }
        });

        ClienteAgregarBt.setText("Cliente");
        ClienteAgregarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteAgregarBtActionPerformed(evt);
            }
        });

        jLabel2.setText("Articulos");

        FamiliarAgregarBt.setText("Familiar");
        FamiliarAgregarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FamiliarAgregarBtActionPerformed(evt);
            }
        });

        GatoAgregarBt.setText("Gato");
        GatoAgregarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GatoAgregarBtActionPerformed(evt);
            }
        });

        BaleadaAgregarBt.setText("Baleada");
        BaleadaAgregarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BaleadaAgregarBtActionPerformed(evt);
            }
        });

        jLabel3.setText("Árbol de personas");

        jScrollPane2.setViewportView(jTree2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(JefeAgregarBt, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmpleadoAgregarBt, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(86, 86, 86)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(GatoAgregarBt, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                            .addComponent(BaleadaAgregarBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(FamiliarAgregarBt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                        .addComponent(ClienteAgregarBt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)))
                .addGap(62, 62, 62)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 298, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(GatoAgregarBt, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                            .addComponent(JefeAgregarBt, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BaleadaAgregarBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EmpleadoAgregarBt, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(ClienteAgregarBt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(FamiliarAgregarBt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Agregar", jPanel2);

        jLabel4.setText("Personas");

        jLabel5.setText("Productos");

        ListarBg.add(JefesListarRb);
        JefesListarRb.setSelected(true);
        JefesListarRb.setText("Jefes");

        ListarBg.add(EmpleadosListarRb);
        EmpleadosListarRb.setText("Empleados");

        ListarBg.add(ClientesListarRb);
        ClientesListarRb.setText("Clientes");

        ListarBg.add(FamiliaresListarRb);
        FamiliaresListarRb.setText("Familiares");
        FamiliaresListarRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FamiliaresListarRbActionPerformed(evt);
            }
        });

        ListarBg.add(GatosListarRb);
        GatosListarRb.setText("Gatos");

        ListarBg.add(BaleadasListarRb);
        BaleadasListarRb.setText("Baleadas");

        TablaListar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "ID", "Edad", "Nacionalidad", "Lugar de nacimiento", "Color de piel"
            }
        ));
        jScrollPane4.setViewportView(TablaListar);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 796, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(JefesListarRb)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(EmpleadosListarRb)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ClientesListarRb)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(FamiliaresListarRb)))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(GatosListarRb)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BaleadasListarRb))
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JefesListarRb)
                    .addComponent(EmpleadosListarRb)
                    .addComponent(ClientesListarRb)
                    .addComponent(FamiliaresListarRb)
                    .addComponent(GatosListarRb)
                    .addComponent(BaleadasListarRb))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Listar", jPanel5);

        jLabel6.setText("Personas");

        jLabel7.setText("Productos");

        ModificarBg.add(JefesModificarRb);
        JefesModificarRb.setSelected(true);
        JefesModificarRb.setText("Jefes");

        ModificarBg.add(EmpleadosModificarRb);
        EmpleadosModificarRb.setText("Empleados");

        ModificarBg.add(ClientesModificarRb);
        ClientesModificarRb.setText("Clientes");

        ModificarBg.add(FamiliaresModificarRb);
        FamiliaresModificarRb.setText("Familiares");

        ModificarBg.add(GatosModificarRb);
        GatosModificarRb.setText("Gatos");

        ModificarBg.add(BaleadasModificarRb);
        BaleadasModificarRb.setText("Baleadas");

        ActualizarControlesModificarBt.setText("Actualizar controles");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jButton8.setText("Guardar Cambios");

        jButton9.setText("Eliminar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(JefesModificarRb)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(EmpleadosModificarRb)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ClientesModificarRb)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(FamiliaresModificarRb))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(ActualizarControlesModificarBt)
                                .addGap(71, 320, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(GatosModificarRb)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BaleadasModificarRb))
                                    .addComponent(jLabel7))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JefesModificarRb)
                    .addComponent(EmpleadosModificarRb)
                    .addComponent(ClientesModificarRb)
                    .addComponent(FamiliaresModificarRb)
                    .addComponent(GatosModificarRb)
                    .addComponent(BaleadasModificarRb))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ActualizarControlesModificarBt))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 249, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        jTabbedPane1.addTab("Modificar", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 835, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 594, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Venta", jPanel4);

        jMenu1.setText("Archivo");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Abrir");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Guardar");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Guardar como");
        jMenu1.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem4.setText("Acerca de");
        jMenu1.add(jMenuItem4);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem5.setText("Salir");
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FamiliaresListarRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FamiliaresListarRbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FamiliaresListarRbActionPerformed

    private void JefeAgregarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JefeAgregarBtActionPerformed
        // TODO add your handling code here:
        EmpleadosTemporal.clear();
        AgregarJefe.setVisible(true);
        AgregarJefe.pack();
        AgregarJefe.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (int i = 0; i < Empleados.size(); i++) {
            modelo.addElement(Empleados.get(i));
        }
        AgregarEmpleadoAgregarJefeCb.setModel(modelo);
    }//GEN-LAST:event_JefeAgregarBtActionPerformed

    private void AgregarEmpleadoAgregarJefeBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarEmpleadoAgregarJefeBtActionPerformed
        // TODO add your handling code here:
        EmpleadosTemporal.add(
                Empleados.get(
                        AgregarEmpleadoAgregarJefeCb.getSelectedIndex()));
    }//GEN-LAST:event_AgregarEmpleadoAgregarJefeBtActionPerformed

    private void AgregarJefeAgregarJefeBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarJefeAgregarJefeBtActionPerformed
        // TODO add your handling code here:
        Jefes.add(new Jefe());
        int pos = Jefes.size() - 1;
        Jefes.get(pos).setNombre(NombreAgregarJefeTf.getText());
        Jefes.get(pos).setID(IDAgregarJefeTf.getText());
        try {
            Jefes.get(pos).setEdad(Integer.parseInt(EdadAgregarJefeTf.getText()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(AgregarJefe, "¡Agregado!");
        }
        Jefes.get(pos).setNacionalidad(NacionalidadAgregarJefeTf.getText());
        Jefes.get(pos).setLugarDeNacimiento(LugarDeNacimientoAgregarJefeTf.getText());
        Jefes.get(pos).setColorDePiel(ColorDePielAgregarJefeBt.getBackground());
        Jefes.get(pos).setSeccionDeTrabajo(
                SeccionDeTrabajoAgregarJefeCb.getItemAt(
                        SeccionDeTrabajoAgregarJefeCb.getSelectedIndex()));
        Jefes.get(pos).setEmpleados(EmpleadosTemporal);
        Personas.add(Jefes.get(pos));
        JOptionPane.showMessageDialog(AgregarJefe, "¡Agregado!");
        AgregarJefe.dispose();
    }//GEN-LAST:event_AgregarJefeAgregarJefeBtActionPerformed

    private void AgregarEmpleadoAgregarEmpleadoBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarEmpleadoAgregarEmpleadoBtActionPerformed
        // TODO add your handling code here:
        Empleados.add(new Empleado());
        int pos = Empleados.size() - 1;
        Empleados.get(pos).setNombre(NombreAgregarEmpleadoTf.getText());
        Empleados.get(pos).setID(IDAgregarEmpleadoTf.getText());
        try {
            Empleados.get(pos).setEdad(Integer.parseInt(EdadAgregarEmpleadoTf.getText()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(AgregarEmpleado, "Hubo un problema con la edad");
        }
        
        Empleados.get(pos).setNacionalidad(NacionalidadAgregarEmpleadoTf.getText());
        Empleados.get(pos).setLugarDeNacimiento(LugarDeNacimientoAgregarEmpleadoTf.getText());
        Empleados.get(pos).setColorDePiel(ColorDePielAgregarEmpleadoBt.getBackground());
        Empleados.get(pos).setSeccionDeTrabajo(
                SeccionDeTrabajoAgregarJefeCb.getItemAt(
                        SeccionDeTrabajoAgregarJefeCb.getSelectedIndex()));
        try {
            Empleados.get(pos).setHoraDeLlegada(
                Integer.parseInt(HoraDeLlegadaAgregarEmpleadoSp.getValue().toString()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(AgregarEmpleado, "Hubo problema con la hora de llegada");
        }
        try {
            Empleados.get(pos).setHoraDeSalida(
                Integer.parseInt(HoraDeSalidaAgregarEmpleadoSp.getValue().toString()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(AgregarEmpleado, "Hubo problema con la hora de salida");
        }
        try {
            Empleados.get(pos).setSueldo(Float.parseFloat(SueldoAgregarEmpleadoTf.getText()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(AgregarEmpleado, "Hubo un problema con el sueldo");
        }
        
        Empleados.get(pos).setEstado(EstadoAgregarEmpleadoCb.getItemAt(
                EstadoAgregarEmpleadoCb.getSelectedIndex()));
        Personas.add(Empleados.get(pos));
        JOptionPane.showMessageDialog(AgregarEmpleado, "¡Agregado!");
        AgregarEmpleado.dispose();
    }//GEN-LAST:event_AgregarEmpleadoAgregarEmpleadoBtActionPerformed

    private void AgregarClienteAgregarClienteBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarClienteAgregarClienteBtActionPerformed
        // TODO add your handling code here:
        Clientes.add(new Cliente());
        int pos = Clientes.size() - 1;
        Clientes.get(pos).setNombre(NombreAgregarClienteTf.getText());
        Clientes.get(pos).setID(IDAgregarClienteTf.getText());
        try {
            Clientes.get(pos).setEdad(Integer.parseInt(EdadAgregarClienteTf.getText()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(AgregarCliente, "Hubo un problema con la edad");
        }
        
        Clientes.get(pos).setNacionalidad(NacionalidadAgregarClienteTf.getText());
        Clientes.get(pos).setLugarDeNacimiento(LugarDeNacimientoAgregarClienteTf.getText());
        Clientes.get(pos).setColorDePiel(ColorDePielAgregarClienteBt.getBackground());
        try {
            Clientes.get(pos).setDinero(Float.parseFloat(DineroAgregarClienteTf.getText()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(AgregarCliente, "Hubo un problema con el dinero");
        }
        Personas.add(Clientes.get(pos));
        JOptionPane.showMessageDialog(AgregarCliente, "¡Agregado!");
        AgregarCliente.dispose();
    }//GEN-LAST:event_AgregarClienteAgregarClienteBtActionPerformed

    private void ClienteAgregarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteAgregarBtActionPerformed
        // TODO add your handling code here:
        AgregarCliente.setVisible(true);
        AgregarCliente.pack();
        AgregarCliente.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        DefaultComboBoxModel modelo1 = new DefaultComboBoxModel();
        for (int i = 0; i < Personas.size(); i++) {
            modelo.addElement(Personas.get(i));
            modelo1.addElement(Personas.get(i));
        }
        FamiliarPadreAgregarFamiliarCb.setModel(modelo);
        FamiliarHijoAgregarFamiliarCb.setModel(modelo1);
    }//GEN-LAST:event_ClienteAgregarBtActionPerformed

    private void AgregarFamiliarHijoAgregarFamiliarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarFamiliarHijoAgregarFamiliarBtActionPerformed
        // TODO add your handling code here:
        FamiliaresTemporal.add(
                Familiares.get(FamiliarHijoAgregarFamiliarCb.getSelectedIndex()));
    }//GEN-LAST:event_AgregarFamiliarHijoAgregarFamiliarBtActionPerformed

    private void AgregarFamiliarAgregarFamiliarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarFamiliarAgregarFamiliarBtActionPerformed
        // TODO add your handling code here:
        Familiares.add(new Familiar());
        int pos = Familiares.size() - 1;
        Familiares.get(pos).setNombre(NombreAgregarFamiliarTf.getText());
        Familiares.get(pos).setID(IDAgregarFamiliarTf.getText());
        try {
            Familiares.get(pos).setEdad(Integer.parseInt(EdadAgregarFamiliarTf.getText()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(AgregarFamiliar, "Hubo un problema con la edad");
        }
        Familiares.get(pos).setNacionalidad(NacionalidadAgregarFamiliarTf.getText());
        Familiares.get(pos).setLugarDeNacimiento(LugarDeNacimientoAgregarFamiliarTf.getText());
        Familiares.get(pos).setColorDePiel(ColorDePielAgregarFamiliarBt.getBackground());
        Familiares.get(pos).setPadre(
                Familiares.get(
                        FamiliarPadreAgregarFamiliarCb.getSelectedIndex()));
        JOptionPane.showMessageDialog(AgregarFamiliar, "¡Agregado!");
        AgregarFamiliar.dispose();
    }//GEN-LAST:event_AgregarFamiliarAgregarFamiliarBtActionPerformed

    private void FamiliarAgregarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FamiliarAgregarBtActionPerformed
        // TODO add your handling code here:
        FamiliaresTemporal.clear();
        AgregarFamiliar.setVisible(true);
        AgregarFamiliar.pack();
        AgregarFamiliar.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        DefaultComboBoxModel modelo1 = new DefaultComboBoxModel();
        for (int i = 0; i < Familiares.size(); i++) {
            modelo.addElement(Familiares.get(i));
            modelo1.addElement(Familiares.get(i));
        }
        FamiliarPadreAgregarFamiliarCb.setModel(modelo);
        FamiliarPadreAgregarFamiliarCb.setModel(modelo1);
    }//GEN-LAST:event_FamiliarAgregarBtActionPerformed

    private void GatoAgregarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GatoAgregarBtActionPerformed
        // TODO add your handling code here:
        AgregarGato.setVisible(true);
        AgregarGato.pack();
        AgregarGato.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_GatoAgregarBtActionPerformed

    private void EmpleadoAgregarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpleadoAgregarBtActionPerformed
        // TODO add your handling code here:
        AgregarEmpleado.setVisible(true);
        AgregarEmpleado.pack();
        AgregarEmpleado.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_EmpleadoAgregarBtActionPerformed

    private void AgregarGatoAgregarGatoBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarGatoAgregarGatoBtActionPerformed
        // TODO add your handling code here:
        Articulos.add(new Gato());
        int pos=Articulos.size()-1;
        try {
            Articulos.get(pos).setPrecio(
            Float.parseFloat(PrecioAgregarGatoTf.getText()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(AgregarGato, "Algo salió mal con el precio");
        }
        try {
            ((Gato)(Articulos.get(pos))).setPeso(
            Float.parseFloat(PrecioAgregarGatoTf.getText()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(AgregarGato, "Algo salió mal con el peso");
        }
        try {
            ((Gato)(Articulos.get(pos))).setAltura(
            Float.parseFloat(AlturaAgregarGatoTf.getText()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(AgregarGato, "Algo salió mal con la altura");
        }
        JOptionPane.showMessageDialog(AgregarGato, "¡Agregado!");
        AgregarGato.dispose();
    }//GEN-LAST:event_AgregarGatoAgregarGatoBtActionPerformed

    private void AgregarIngredienteAgregarBaleadaBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarIngredienteAgregarBaleadaBtActionPerformed
        // TODO add your handling code here:
        IngredientesTemporal.add(IngredienteAgregarBaleadaTf.getText());
    }//GEN-LAST:event_AgregarIngredienteAgregarBaleadaBtActionPerformed

    private void AgregarBaleadaAgregarBaleadaBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarBaleadaAgregarBaleadaBtActionPerformed
        // TODO add your handling code here:
        Articulos.add(new Baleada());
        int pos=Articulos.size()-1;
        try {
            Articulos.get(pos).setPrecio(
            Float.parseFloat(PrecioAgregarBaleadaTf.getText()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(AgregarBaleada, "Hubo un problema con el precio");
        }
        ((Baleada)Articulos.get(pos)).setIngredientes(IngredientesTemporal);
        JOptionPane.showMessageDialog(AgregarBaleada, "¡Agregado!");
        AgregarBaleada.dispose();
    }//GEN-LAST:event_AgregarBaleadaAgregarBaleadaBtActionPerformed

    private void BaleadaAgregarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BaleadaAgregarBtActionPerformed
        // TODO add your handling code here:
        AgregarBaleada.setVisible(true);
        AgregarBaleada.pack();
        IngredientesTemporal.clear();
    }//GEN-LAST:event_BaleadaAgregarBtActionPerformed
    ArrayList<String> IngredientesTemporal=new ArrayList();
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActualizarControlesModificarBt;
    private javax.swing.JDialog AgregarBaleada;
    private javax.swing.JButton AgregarBaleadaAgregarBaleadaBt;
    private javax.swing.JDialog AgregarCliente;
    private javax.swing.JButton AgregarClienteAgregarClienteBt;
    private javax.swing.JDialog AgregarEmpleado;
    private javax.swing.JButton AgregarEmpleadoAgregarEmpleadoBt;
    private javax.swing.JButton AgregarEmpleadoAgregarJefeBt;
    private javax.swing.JComboBox<String> AgregarEmpleadoAgregarJefeCb;
    private javax.swing.JDialog AgregarFamiliar;
    private javax.swing.JButton AgregarFamiliarAgregarFamiliarBt;
    private javax.swing.ButtonGroup AgregarFamiliarBg;
    private javax.swing.ButtonGroup AgregarFamiliarBg1;
    private javax.swing.JButton AgregarFamiliarHijoAgregarFamiliarBt;
    private javax.swing.JDialog AgregarGato;
    private javax.swing.JButton AgregarGatoAgregarGatoBt;
    private javax.swing.JButton AgregarIngredienteAgregarBaleadaBt;
    private javax.swing.JDialog AgregarJefe;
    private javax.swing.JButton AgregarJefeAgregarJefeBt;
    private javax.swing.JTextField AlturaAgregarGatoTf;
    private javax.swing.JButton BaleadaAgregarBt;
    private javax.swing.JRadioButton BaleadasListarRb;
    private javax.swing.JRadioButton BaleadasModificarRb;
    private javax.swing.JButton ClienteAgregarBt;
    private javax.swing.JRadioButton ClientesListarRb;
    private javax.swing.JRadioButton ClientesModificarRb;
    private javax.swing.JButton ColorDePielAgregarClienteBt;
    private javax.swing.JButton ColorDePielAgregarEmpleadoBt;
    private javax.swing.JButton ColorDePielAgregarFamiliarBt;
    private javax.swing.JButton ColorDePielAgregarJefeBt;
    private javax.swing.JTextField DineroAgregarClienteTf;
    private javax.swing.JTextField EdadAgregarClienteTf;
    private javax.swing.JTextField EdadAgregarEmpleadoTf;
    private javax.swing.JTextField EdadAgregarFamiliarTf;
    private javax.swing.JTextField EdadAgregarJefeTf;
    private javax.swing.JButton EmpleadoAgregarBt;
    private javax.swing.JRadioButton EmpleadosListarRb;
    private javax.swing.JRadioButton EmpleadosModificarRb;
    private javax.swing.JComboBox<String> EstadoAgregarEmpleadoCb;
    private javax.swing.JButton FamiliarAgregarBt;
    private javax.swing.JComboBox<String> FamiliarHijoAgregarFamiliarCb;
    private javax.swing.JComboBox<String> FamiliarPadreAgregarFamiliarCb;
    private javax.swing.JRadioButton FamiliaresListarRb;
    private javax.swing.JRadioButton FamiliaresModificarRb;
    private javax.swing.JButton GatoAgregarBt;
    private javax.swing.JRadioButton GatosListarRb;
    private javax.swing.JRadioButton GatosModificarRb;
    private javax.swing.JSpinner HoraDeLlegadaAgregarEmpleadoSp;
    private javax.swing.JSpinner HoraDeSalidaAgregarEmpleadoSp;
    private javax.swing.JTextField IDAgregarClienteTf;
    private javax.swing.JTextField IDAgregarEmpleadoTf;
    private javax.swing.JTextField IDAgregarFamiliarTf;
    private javax.swing.JTextField IDAgregarJefeTf;
    private javax.swing.JTextField IngredienteAgregarBaleadaTf;
    private javax.swing.JButton JefeAgregarBt;
    private javax.swing.JRadioButton JefesListarRb;
    private javax.swing.JRadioButton JefesModificarRb;
    private javax.swing.ButtonGroup ListarBg;
    private javax.swing.JTextField LugarDeNacimientoAgregarClienteTf;
    private javax.swing.JTextField LugarDeNacimientoAgregarEmpleadoTf;
    private javax.swing.JTextField LugarDeNacimientoAgregarFamiliarTf;
    private javax.swing.JTextField LugarDeNacimientoAgregarJefeTf;
    private javax.swing.ButtonGroup ModificarBg;
    private javax.swing.JTextField NacionalidadAgregarClienteTf;
    private javax.swing.JTextField NacionalidadAgregarEmpleadoTf;
    private javax.swing.JTextField NacionalidadAgregarFamiliarTf;
    private javax.swing.JTextField NacionalidadAgregarJefeTf;
    private javax.swing.JTextField NombreAgregarClienteTf;
    private javax.swing.JTextField NombreAgregarEmpleadoTf;
    private javax.swing.JTextField NombreAgregarFamiliarTf;
    private javax.swing.JTextField NombreAgregarJefeTf;
    private javax.swing.JTextField PesoAgregarGatoTf;
    private javax.swing.JTextField PrecioAgregarBaleadaTf;
    private javax.swing.JTextField PrecioAgregarGatoTf;
    private javax.swing.JComboBox<String> SeccionDeTrabajoAgregarJefeCb;
    private javax.swing.JTextField SueldoAgregarEmpleadoTf;
    private javax.swing.JTable TablaListar;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTree jTree1;
    private javax.swing.JTree jTree2;
    private javax.swing.JTree jTree3;
    private javax.swing.JTree jTree4;
    private javax.swing.JTree jTree5;
    // End of variables declaration//GEN-END:variables
    static ArrayList<Persona> Personas = new ArrayList();
    static ArrayList<Jefe> Jefes = new ArrayList();
    static ArrayList<Empleado> Empleados = new ArrayList();
    static ArrayList<Cliente> Clientes = new ArrayList();
    static ArrayList<Familiar> Familiares = new ArrayList();
    static ArrayList<Articulo> Articulos = new ArrayList();

    static ArrayList<Empleado> EmpleadosTemporal = new ArrayList();
    static ArrayList<Familiar> FamiliaresTemporal = new ArrayList();

}
